import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { SearchForm } from "@/components/search-form";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
              <div className="flex items-center gap-2 px-3">
                <SidebarTrigger />
              </div>
              <div className="grow h-4" />
              <SearchForm />
              <div className="flex pr-4">
                <Button asChild variant="link" className="p-2">
                  <Link href="/login">Login</Link>
                </Button>

                <Button asChild variant="link" className="p-2">
                  <Link href="/signup">Sign Up</Link>
                </Button>
              </div>
            </header>
            <main className="flex flex-1 flex-col gap-4 p-4">{children}</main>
            <footer
              id="footer"
              className="flex mw-footer justify-between"
              role="contentinfo"
            >
              <ul id="footer-info">
                <li>
                  <p>
                    This is a wiki page for{" "}
                    <b className="text-red-800">The Saga of Vizima</b> dungeons
                    and dragons campain
                  </p>
                </li>
                <li>
                  Created and maintained by Trent Mokoena for more info{" "}
                  <b>
                    <Link href="https://github.com/suburban-loner">
                      click here
                    </Link>
                  </b>
                </li>
              </ul>
              <Link href="#">
                <div className="flex items-center justify-center">
                  <Image
                    src="/Footer-Logo.jpg"
                    alt="Footer logo for the dnd campaign."
                    width={100}
                    height={100}
                    className="rounded-full justify-end"
                  />
                </div>
              </Link>
            </footer>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
